# Generated by Django 4.2.1 on 2023-05-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_is_out_alter_person_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_out',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='post',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='solve_num',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_num',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
