# Generated by Django 4.2.1 on 2023-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_houseinfo_address_houseinfo_belong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='license',
            field=models.ImageField(upload_to='license/'),
        ),
    ]
