# Generated by Django 4.2.1 on 2023-05-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_houseinfo_is_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_out',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='post',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='solve_num',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_num',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
