# Generated by Django 4.2.1 on 2023-05-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_person_is_out_alter_person_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('男', '女')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='work_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
