# Generated by Django 4.2.1 on 2023-05-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_person_gender_alter_person_work_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='work_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
