# Generated by Django 4.2.1 on 2023-05-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_person_work_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_out',
            field=models.CharField(blank=True, choices=[('是', '是'), ('否', '否')], max_length=1, null=True),
        ),
    ]
